#!/bin/bash

# Enable the script (yes/no)?
ENABLED='no'

# Install MySQL Server (yes/no)?
# MySQL Client is installed by default to allow
# the connection between PHP and the MySQL server.
INSTALL_MYSQL='no'

# Install Postfix (yes/no)?
# Postfix will be installed as a null (send-only) client. It will not receive
# any emails.
INSTALL_POSTFIX='yes'

### Directories ###############################################################

# Destination directory (where to install the software)
DESTINATION_DIR='/opt'

# Web files directory
WEB_DIR='/var/www'

###############################################################################

### Program Versions: #########################################################

# NginX Version:
# Ex: NGINX_VERSION='1.2.2'
NGINX_VERSION='1.3.3'

# PHP Version:
# Ex: PHP_VERSION='5.3.15'
PHP_VERSION='5.4.5'

# APC Version:
# Ex: APC_VERSION='3.1.10'
APC_VERSION='3.1.11'

# Suhosin Version:
# Ex: SUHOSIN_VERSION='0.9.33'
SUHOSIN_VERSION='0.9.33'

###############################################################################


