#!/bin/bash

if ! [ $1 ]; then exit; fi

# Check if you are root
if [ $(id -u) != "0" ]; then
  echo "Error: You must be root to run this command."
  echo "Error: Please use 'sudo'."
  exit 1
fi

for site in $*; do
  
  # Check if already enabled
  if [ -f /etc/nginx/sites-enabled/$site ]; then
    echo "$site is already enabled"; continue
  fi
  
  # Check if file exists
  if [ -f /etc/nginx/sites-available/$site ]; then
    echo "Enabling $site"
    ln -s /etc/nginx/sites-available/$site /etc/nginx/sites-enabled/$site
  else
    echo "no such file: /opt/nginx/sites-available/$site"
  fi
  
done

echo "Do you want to restart Nginx? [Y/n]: "
read  answer
case  $answer in 'n'|'N'|'No'|'no') exit ;; esac

/etc/init.d/nginx restart
