#!/bin/sh

### BEGIN INIT INFO
# Provides:          php-fpm php5-fpm
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts php-fpm
### END INIT INFO

set -u

INSTALL_DIR="/opt/php5"
DAEMON="PHP5 FPM"
FPM_CMD=$INSTALL_DIR/sbin/php-fpm
FPM_CONF=/etc/php5/php-fpm.conf
FPM_PID=/var/run/php-fpm.pid
TIMEOUT=30

FPM_OPTIONS="--fpm-config $FPM_CONF"
SSD_OPTIONS="--oknodo --quiet --pidfile $FPM_PID --exec $FPM_CMD"

. /lib/lsb/init-functions

case "$1" in
    start)
  log_begin_msg "Starting $DAEMON..."

  /sbin/start-stop-daemon --start $SSD_OPTIONS -- $FPM_OPTIONS
  log_end_msg $?
    ;;
    stop)
  log_begin_msg "Stopping $DAEMON..."

  /sbin/start-stop-daemon --stop $SSD_OPTIONS
  log_end_msg $?
    ;;
    graceful-stop)
  log_begin_msg "Gracefully stopping $DAEMON..."

  /sbin/start-stop-daemon --stop --retry QUIT/$TIMEOUT/TERM $SSD_OPTIONS
  log_end_msg $?
    ;;
    restart)
  $0 stop
  sleep 1
  $0 start
    ;;
    reload|force-reload)
  log_begin_msg "Reloading $DAEMON..."

  /sbin/start-stop-daemon --stop --signal USR2 $SSD_OPTIONS
  log_end_msg $?
    ;;
    *)
  echo "Usage: $0 {start|stop|graceful-stop|restart|reload|force-reload}"
  exit 1
    ;;
esac
